version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - procurement

  db:
    image: postgres:13-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - procurement

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - procurement

  celery-worker:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - procurement

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    networks:
      - procurement

volumes:
  postgres_data:
  redis_data:

networks:
  procurement:
    driver: bridge